-- Concede todas as permissões ao usuário administrador (user_id: 68d877c6-7039-4d96-8ba6-215a21d34df8)

INSERT INTO public.permissions (
  user_id,
  gerenciar_usuarios,
  gerenciar_grupos,
  criar_projetos,
  editar_projetos,
  excluir_projetos,
  visualizar_todos_projetos,
  visualizar_documentos,
  criar_documentos,
  editar_documentos,
  excluir_documentos,
  download_documentos,
  compartilhar_documentos,
  criar_templates,
  editar_templates,
  excluir_templates,
  assinar_documentos,
  solicitar_assinatura,
  alimentar_ia,
  gerenciar_ia,
  acesso_total
) VALUES (
  '68d877c6-7039-4d96-8ba6-215a21d34df8'::uuid,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true
)
ON CONFLICT (user_id) DO UPDATE SET
  gerenciar_usuarios = true,
  gerenciar_grupos = true,
  criar_projetos = true,
  editar_projetos = true,
  excluir_projetos = true,
  visualizar_todos_projetos = true,
  visualizar_documentos = true,
  criar_documentos = true,
  editar_documentos = true,
  excluir_documentos = true,
  download_documentos = true,
  compartilhar_documentos = true,
  criar_templates = true,
  editar_templates = true,
  excluir_templates = true,
  assinar_documentos = true,
  solicitar_assinatura = true,
  alimentar_ia = true,
  gerenciar_ia = true,
  acesso_total = true;
