-- Template "Especificação de Requisitos" — alinhado ao fluxo da IA
-- Trava: is_protected=true (não pode ser excluído)
-- Restauração: original_sections guarda cópia para restaurar ao formato original
-- Spec: Spec/Spec_Especificacao_Requisitos.md

DO $$
DECLARE
  v_html text :=
    '<h1 style="text-align:center;font-weight:700">Especificação de Requisitos</h1>'
    '<p><br></p>'
    '<h2>1. Título do Documento</h2>'
    '<div class="sgid-metadata-field" contenteditable="false"'
    ' data-field-id="sec-titulo" data-field-title="1. Título do Documento"'
    ' data-field-help="Nome completo do documento. Ex: Especificação de Requisitos — Sistema X."'
    ' data-topic-id="">'
    '<div class="sgid-metadata-field__header"><div class="sgid-metadata-field__title">1. Título do Documento</div>'
    '<div class="sgid-metadata-field__help" style="font-size:10px;opacity:0.7">Nome completo do documento.</div></div>'
    '<div class="sgid-metadata-field__textarea">Digite aqui...</div>'
    '</div>'
    '<p><br></p>'
    '<h2>2. Projeto</h2>'
    '<div class="sgid-metadata-field" contenteditable="false"'
    ' data-field-id="sec-projeto" data-field-title="2. Projeto"'
    ' data-field-help="Nome do sistema ou projeto. Ex: Portal do Cidadão."'
    ' data-topic-id="">'
    '<div class="sgid-metadata-field__header"><div class="sgid-metadata-field__title">2. Projeto</div>'
    '<div class="sgid-metadata-field__help" style="font-size:10px;opacity:0.7">Nome do sistema ou projeto.</div></div>'
    '<div class="sgid-metadata-field__textarea">Digite aqui...</div>'
    '</div>'
    '<p><br></p>'
    '<h2>3. Histórico de Versões</h2>'
    '<table style="border-collapse:collapse;width:100%;margin:12px 0">'
    '<tbody>'
    '<tr>'
    '<th style="border:1px solid #ccc;padding:6px 10px;background:#f3f4f6;font-weight:600">Versão</th>'
    '<th style="border:1px solid #ccc;padding:6px 10px;background:#f3f4f6;font-weight:600">Tipo</th>'
    '<th style="border:1px solid #ccc;padding:6px 10px;background:#f3f4f6;font-weight:600">Data</th>'
    '<th style="border:1px solid #ccc;padding:6px 10px;background:#f3f4f6;font-weight:600">Autor</th>'
    '</tr>'
    '<tr>'
    '<td style="border:1px solid #ccc;padding:6px 10px"></td>'
    '<td style="border:1px solid #ccc;padding:6px 10px"></td>'
    '<td style="border:1px solid #ccc;padding:6px 10px"></td>'
    '<td style="border:1px solid #ccc;padding:6px 10px"></td>'
    '</tr>'
    '</tbody>'
    '</table>'
    '<p><br></p>'
    '<h2>4. Introdução</h2>'
    '<div class="sgid-metadata-field" contenteditable="false"'
    ' data-field-id="sec-introducao" data-field-title="4. Introdução"'
    ' data-field-help="Objetivo, público-alvo e organização do documento. Apenas conteúdo desta seção."'
    ' data-topic-id="">'
    '<div class="sgid-metadata-field__header"><div class="sgid-metadata-field__title">4. Introdução</div>'
    '<div class="sgid-metadata-field__help" style="font-size:10px;opacity:0.7">Objetivo, público-alvo e organização.</div></div>'
    '<div class="sgid-metadata-field__textarea">Digite aqui...</div>'
    '</div>'
    '<p><br></p>'
    '<h2>5. Visão Geral do Sistema</h2>'
    '<div class="sgid-metadata-field" contenteditable="false"'
    ' data-field-id="sec-visao" data-field-title="5. Visão Geral do Sistema"'
    ' data-field-help="O que é o sistema, para quem e qual problema resolve. Apenas conteúdo desta seção."'
    ' data-topic-id="">'
    '<div class="sgid-metadata-field__header"><div class="sgid-metadata-field__title">5. Visão Geral do Sistema</div>'
    '<div class="sgid-metadata-field__help" style="font-size:10px;opacity:0.7">O que é, para quem e qual problema resolve.</div></div>'
    '<div class="sgid-metadata-field__textarea">Digite aqui...</div>'
    '</div>'
    '<p><br></p>'
    '<h2>6. Escopo do Projeto</h2>'
    '<div class="sgid-metadata-field" contenteditable="false"'
    ' data-field-id="sec-escopo" data-field-title="6. Escopo do Projeto"'
    ' data-field-help="O que está incluído e o que está fora do escopo. Apenas conteúdo desta seção."'
    ' data-topic-id="">'
    '<div class="sgid-metadata-field__header"><div class="sgid-metadata-field__title">6. Escopo do Projeto</div>'
    '<div class="sgid-metadata-field__help" style="font-size:10px;opacity:0.7">Incluído e fora do escopo.</div></div>'
    '<div class="sgid-metadata-field__textarea">Digite aqui...</div>'
    '</div>'
    '<p><br></p>'
    '<h2>7. Organização dos Requisitos</h2>'
    '<p>Estrutura: Épico (EP) → Feature (FT) → História de Usuário (HU) → Requisito Funcional (RF).</p>'
    '<p><br></p>'
    '<h2>8. Estrutura de Requisitos</h2>'
    '<p><br></p>'
    '<div class="sgid-metadata-field" contenteditable="false"'
    ' data-field-id="sec-epico" data-field-title="Épico (EP)"'
    ' data-field-help="Épico: gerado pela IA com base na base de conhecimento. Apenas conteúdo desta seção."'
    ' data-topic-id="" data-repeatable="true"'
    ' data-planning-instruction="Liste todos os épicos/grandes objetivos funcionais identificados na documentação do projeto">'
    '<div class="sgid-metadata-field__header">'
    '<div class="sgid-metadata-field__title">Épico (EP)'
    '<span style="font-size:9px;background:#dbeafe;color:#1d4ed8;padding:1px 6px;border-radius:99px;margin-left:6px;font-weight:600">REPETÍVEL</span>'
    '</div>'
    '<div class="sgid-metadata-field__help" style="font-size:10px;opacity:0.7">Épico: gerado pela IA</div>'
    '</div>'
    '<div class="sgid-metadata-field__textarea">Campo dinâmico — a IA criará as instâncias necessárias.</div>'
    '</div>'
    '<p><br></p>'
    '<div class="sgid-metadata-field" contenteditable="false"'
    ' data-field-id="sec-feature" data-field-title="Feature (FT)"'
    ' data-field-help="Feature: gerado pela IA com base na base de conhecimento. Apenas conteúdo desta seção."'
    ' data-topic-id="" data-repeatable="true"'
    ' data-planning-instruction="Liste todas as features/funcionalidades identificadas na documentação do projeto">'
    '<div class="sgid-metadata-field__header">'
    '<div class="sgid-metadata-field__title">Feature (FT)'
    '<span style="font-size:9px;background:#dbeafe;color:#1d4ed8;padding:1px 6px;border-radius:99px;margin-left:6px;font-weight:600">REPETÍVEL</span>'
    '</div>'
    '<div class="sgid-metadata-field__help" style="font-size:10px;opacity:0.7">Feature: gerado pela IA</div>'
    '</div>'
    '<div class="sgid-metadata-field__textarea">Campo dinâmico — a IA criará as instâncias necessárias.</div>'
    '</div>'
    '<p><br></p>'
    '<div class="sgid-metadata-field" contenteditable="false"'
    ' data-field-id="sec-hu" data-field-title="História de Usuário (HU)"'
    ' data-field-help="HU: gerado pela IA. Formato: Como [perfil], quero [ação], para [objetivo]. Apenas conteúdo desta seção."'
    ' data-topic-id="" data-repeatable="true"'
    ' data-planning-instruction="Liste todas as histórias de usuário identificadas na documentação do projeto">'
    '<div class="sgid-metadata-field__header">'
    '<div class="sgid-metadata-field__title">História de Usuário (HU)'
    '<span style="font-size:9px;background:#dbeafe;color:#1d4ed8;padding:1px 6px;border-radius:99px;margin-left:6px;font-weight:600">REPETÍVEL</span>'
    '</div>'
    '<div class="sgid-metadata-field__help" style="font-size:10px;opacity:0.7">HU: gerado pela IA</div>'
    '</div>'
    '<div class="sgid-metadata-field__textarea">Campo dinâmico — a IA criará as instâncias necessárias.</div>'
    '</div>'
    '<p><br></p>'
    '<div class="sgid-metadata-field" contenteditable="false"'
    ' data-field-id="sec-rf" data-field-title="Requisito Funcional (RF)"'
    ' data-field-help="RF: gerado pela IA com base na base de conhecimento. Apenas conteúdo desta seção."'
    ' data-topic-id="" data-repeatable="true"'
    ' data-planning-instruction="Liste todos os requisitos funcionais identificados na documentação do projeto">'
    '<div class="sgid-metadata-field__header">'
    '<div class="sgid-metadata-field__title">Requisito Funcional (RF)'
    '<span style="font-size:9px;background:#dbeafe;color:#1d4ed8;padding:1px 6px;border-radius:99px;margin-left:6px;font-weight:600">REPETÍVEL</span>'
    '</div>'
    '<div class="sgid-metadata-field__help" style="font-size:10px;opacity:0.7">RF: gerado pela IA</div>'
    '</div>'
    '<div class="sgid-metadata-field__textarea">Campo dinâmico — a IA criará as instâncias necessárias.</div>'
    '</div>'
    '<p><br></p>';
  v_sections jsonb;
  v_original jsonb;
BEGIN
  v_sections := jsonb_build_object('html', v_html);
  v_original := v_sections;

  IF NOT EXISTS (SELECT 1 FROM public.templates WHERE nome = 'Especificação de Requisitos' AND global = true) THEN
    INSERT INTO public.templates (nome, tipo_documento, sections, global, project_id, file_url, ai_guidance, spec_path, is_protected, original_sections)
    VALUES (
      'Especificação de Requisitos',
      'Requisitos',
      v_sections,
      true,
      NULL,
      '',
      'Documento de requisitos estruturado em Épico (EP) → Feature (FT) → História de Usuário (HU) → Requisito Funcional (RF). '
      'A IA planeja a estrutura consultando a base de conhecimento, expande seções repetíveis e gera cada seção sequencialmente. '
      'Numeração: EP01, FT01, HU001, RF01. Siga rigorosamente o Spec associado. '
      'IMPORTANTE: Cada seção é parte de um único documento. Não repita introduções ou visão geral em seções posteriores.',
      'Spec/Spec_Especificacao_Requisitos.md',
      true,
      v_original
    );
  END IF;
END $$;
